# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


try:
    HALFSIB = dict()
    GROUP = []
    with open(config["halfsib"], "r") as f:
        for idx, line in enumerate(f, start=1):
            group = line.strip().split(",")
            group_name = f"branch{idx:02d}"
            GROUP.append(group_name)
            HALFSIB[group_name] = group

except FileNotFoundError:
    msg = f"{config["halfsib"]} not found. Please ensure it exists and is correctly formatted."
    raise FileNotFoundError(msg)


with open(config["phenotype"], "r") as f:
    line = f.readline()
    line = line.strip().split("\t")
    if line[0] != "FID" and line[1] != "IID":
        msg = "Make sure FID and IID in the first line of phenotype file. And split by tab."
        raise ValueError(msg)
PHENOTYPE = config["phenotype_names"]


include: "rules/prepare.smk"
include: "rules/regenie.smk"
include: "rules/gcta.smk"
include: "rules/emmax.smk"


onstart:
    print(f"{len(GROUP)} groups found in {config['halfsib']}")
    print(f"Phenotype: {PHENOTYPE}")
    print(f"Software: {', '.join(config['software'])}")


# target rules
# -----------------------------------------------------
rule all:
    input:
        # REGENIE results
        expand(
            "results/{run_id}/{group}/{phenotype}/{software}/manhattan.png",
            phenotype=PHENOTYPE,
            run_id=config["run_id"],
            group=GROUP,
            software=config["software"],
        ),
    default_target: True
