run_id: "Test"
halfsib: "config/empty.csv"
phenotype: "phenotype/sh_f1_restorer_new_replaced.phen"

phenotypes:
  - PlantHeight
  - StemLength
  - PanicleNeckLength
  - FlagLeafLength
  - FlagLeafWidth
  - PanicleNumber
  - StemDiameterLength
  - StemDiameterWidth
  - StrawWeight
  - GrainToStrawRatio
  - YieldPerPlant
  - KiloGrainWeight
  - SeedSettingRate
  - TotalGrainNumberPerPanicle
  - FullGrainNumberPerPanicle
  - TotalGrainNumber
  - EmptyGrainNumber
  - FullGrainNumber
  - GrainShape
  - GrainLength
  - GrainWidth
  - GrainArea
  - Perimeter
  - Roundness

bfile:
  step1: "bfile/6983_train_xiansub_LDfilter"
  step2: "bfile/6983_train_xiansub"

pca: 5

plink2:
  pca_threads: 1

# global transform applied to every phenotype: iint | dint | none
transform: "iint"

gelex:
  grm_threads: 1
  assoc_threads: 1
